### ISSUE TITLE
Update properties order

### ISSUE THREAD

**Issue by racse1** [kraftvaerk/stylelint-config-kraftvaerk#3]
Hi 😃 Sometimes I find myself struggling a lot with our current properties order. Here're few examples:

**1.** `border-right` is before `border-left` which makes sense (top, right, bottom, left), but `border-bottom-right-radius` has to go after `border-bottom-left-radius`. It'd be nice if we can apply same logic everywhere.

![](https://trello-attachments.s3.amazonaws.com/5ac74c198ed67ad96b8f02f8/5ace13bc89ff935f647a3a2e/b576629fe52d1673ecfc90dd372226a9/border-1.png)

**2.** Linter tells me that `border` comes before `border-radius`. But if I have use `border-bottom` and `border-bottom-left-radius`, then `border-bottom-left-radius` has to go first, why?

![](https://trello-attachments.s3.amazonaws.com/5ac74c198ed67ad96b8f02f8/5ace13bc89ff935f647a3a2e/ae389cd27211fd074599ecb62761b99d/border-2.png)

It'd be nice if we can align stuff like that and update the config if needed 😃

**Comment by racse1** [comment]
Maybe we can just borrow [the entire set from Bootstrap](https://github.com/twbs/bootstrap/blob/v4-dev/.stylelintrc#L37-L247) 😸

**Comment by racse1** [comment]
Also there's [stylelint-config-primer](https://github.com/primer/primer/tree/master/tools/stylelint-config-primer) which is maintained by GitHub and has the same properties order as Bootstrap which follows [Code Guide by @mdo](http://codeguide.co/#css-declaration-order) (no surprise why 😄).

**Comment by racse1** [comment]
@mi2oon What do you think https://github.com/racse1/stylelint-config-kraftvaerk/blob/properties-order/index.js?

**Comment by mi2oon** [comment]
@racse1: I love it. I actually never liked the fact that we had to maintain the order ourselves especially when there are new things coming in such as grid. I also prefer the use on primer config as an extend. Just hope there aren't many lint warnings on actively running projects 😈 💯 😄

**Comment by mi2oon** [comment]
@racse1 I just had a closer look at `stylelint-config-primer` and it seems a few plugins. this means we would increase other depencedies. I therefore suggest we make our own list. Borrowing from both the bootstrap and primer whatever makes sense. I had make a list and we can take it from there.

**Comment by racse1** [comment]
@mi2oon Cool, yeah, that was my idea as well. 

> I also prefer the use on primer config as an extend.

We might try that, but I haven't looked into the config itself. My initial idea was to just borrow the the properties order. In any case I think most of the issue are going to be fixed automatically.

**Comment by racse1** [comment]
@mi2oon 

> this means we would increase other depencedies

So far that's what we only need:

1. https://github.com/racse1/stylelint-config-kraftvaerk/blob/properties-order/package.json#L47
2. https://github.com/racse1/stylelint-config-kraftvaerk/blob/properties-order/index.js#L3

So we don't actually have to directly depend on any plugins. Or I misunderstood your point? 😄

**Comment by PelleLagermann** [comment]
I think I'd go crazy following the order in the file above :) 
The order is mostly fine I think, but a few of the property-groups are just weird.

I much prefer to keep properties that affect the "box" at the top, then have properties that affect the "content" after that and finally all the swag that don't really affect neither the box nor content (shadows, transitions etc.).   
As such, having display and position close to the top makes perfekt sense, as we are styling from the general to the specifik or in other words, from the outside in. 

Not sure if that makes any sense, but to give a few examples of what I'd change, I'd prefer to have:
 - margin before padding, because that's the way the box-model works and looking at the element you are styling, that is the order in which the properties work. 
 - border grouped with margin and padding because... box-model. Personally I'd place border between margin and padding, but I', also totally fine with having it after padding. 
 - outline nearer to border, as the two are pretty closely related. 
 - background properties before font/text properties as background is the "box" and font/text is the "content"

**Comment by racse1** [comment]
@mi2oon I'm fine with copy-pasting the set, that will fix the issues I initially listed 😄 However, it won't be any different from the current setup — it'll get outdated at some point.

As for the order itself, personally, I usually rely on something that (a) I don't have to maintain and (b) has some recognition within the community, hence my preference is to follow order from mdo's Code Guide as close as possible, so we don't ever bother updating the set on our own (and you can always say, hey, we're using this style guide here — and it won't sound opinionated 😄).

I see where @PelleLagermann is coming from, I've seen similar approach proposed by necolas in [Principles of writing consistent, idiomatic CSS](https://github.com/necolas/idiomatic-css). However, I haven't seen a complete properties order made in accordance to that guide. It'd be nice to find it though, the guide is pretty good (however, later necolas himself started using [alphabetical order](https://github.com/suitcss/suit/blob/master/doc/STYLE.md#declaration-order), which, I imagine, is very painful).

**Comment by akoreshkov** [comment]
for me it would make sense to do following changes:
- `float` and `clear` close to each other since they may work together
- `line-height` right after `font-size` for more convenient calculations
- `transform` before `transition` properties to have everything that can be animated before `transition`/`animation`
- `color` before `font` as it was before
- `flex` properties right after `display` since in most cases they depend on `display: flex` and may affect content distribution as well as `position`
- `z-index` to the group of `position` properties

**Comment by mi2oon** [comment]
@akoreshkov Some of it surely makes sense. Have a look at my changes to the list above. 👍 

- float and clear close to each other makes sense.
- line-height and font-size: didn't change it as I think all font stuff should come before.
- transform before transition: changed
- color before font: changed
- flex right after display. I've decided to keep the flex where it is as display can be many other things. eg. grid. In that case we should move grid props. up too.
- z-index close to position: changed
